# Generated by Django 4.0.5 on 2022-06-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_at',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
