# Generated by Django 4.0.5 on 2022-06-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_project_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
